name: CI

on:
  push:
    branches: master

jobs:
  build-container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code files
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: mbahurau
        password: EDcv7423m?
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          mbahurau/testapp:${{github.sha}}
          mbahurau/testapp:latest

